const people = [
  {
    _id: "1",
    name: "John Doe",
    image: "/images/People/avatar1.jpg",
    gender: "male",
    dob: "2022-08-07",
    country: "India",
    city: "Pune",
    aiDisease: "xyz",
    diagnosedOn: "1999-12-23",
    emailid: "abc@gmail.com",
    pass: "1234",
    phoneNumber: "435678765",
    patient0OrGaurdian1: 1,
    adminApproved: 1,
    bio: "",
    aiStory: "",
    treatment: "",
    impactOfAi: "",
    gram: "",
    photo: "",
  },
  {
    _id: "2",
    name: "Jane Eyre",
    image: "/images/People/avatar2.jpg",
    gender: "female",
    dob: "2020-04-27",
    country: "India",
    city: "Pune",
    aiDisease: "xyz",
    diagnosedOn: "1999-12-23",
    emailid: "abc@gmail.com",
    pass: "1234",
    phoneNumber: "435678765",
    patient0OrGaurdian1: 1,
    adminApproved: 0,
    bio: "",
    aiStory: "",
    treatment: "",
    impactOfAi: "",
    gram: "",
    photo: "",
  },
  {
    _id: "3",
    name: "Salvatore Mavin",
    image: "/images/People/avatar3.jpg",
    gender: "male",
    dob: "2020-04-27",
    country: "India",
    city: "Pune",
    aiDisease: "xyz",
    diagnosedOn: "1999-12-23",
    emailid: "abc@gmail.com",
    pass: "1234",
    phoneNumber: "435678765",
    patient0OrGaurdian1: 1,
    adminApproved: 0,
    bio: "",
    aiStory: "",
    treatment: "",
    impactOfAi: "",
    gram: "",
    photo: "",
  },
  {
    _id: "4",
    name: "Zoey Holloway",
    image: "/images/People/avatar4.jpg",
    gender: "female",
    dob: "2020-04-27",
    country: "India",
    city: "Pune",
    aiDisease: "xyz",
    diagnosedOn: "1999-12-23",
    emailid: "abc@gmail.com",
    pass: "1234",
    phoneNumber: "435678765",
    patient0OrGaurdian1: 1,
    adminApproved: 0,
    bio: "",
    aiStory: "",
    treatment: "",
    impactOfAi: "",
    gram: "",
    photo: "",
  },
  {
    _id: "5",
    name: "Bianka Ray",
    image: "/images/People/avatar5.jpg",
    gender: "female",
    dob: "2020-04-27",
    country: "India",
    city: "Pune",
    aiDisease: "xyz",
    diagnosedOn: "1999-12-23",
    emailid: "abc@gmail.com",
    pass: "1234",
    phoneNumber: "435678765",
    patient0OrGaurdian1: 1,
    adminApproved: 1,
    bio: "",
    aiStory: "",
    treatment: "",
    impactOfAi: "",
    gram: "",
    photo: "",
  },
  {
    _id: "6",
    name: "Sam Jacob",
    image: "/images/People/avatar6.jpg",
    gender: "female",
    dob: "2020-04-27",
    country: "India",
    city: "Pune",
    aiDisease: "xyz",
    diagnosedOn: "1999-12-23",
    emailid: "abc@gmail.com",
    pass: "1234",
    phoneNumber: "435678765",
    patient0OrGaurdian1: 1,
    adminApproved: 1,
    bio: "",
    aiStory: "",
    treatment: "",
    impactOfAi: "",
    gram: "",
    photo: "",
  },
];

export default people;
